# © 2026 CoAssisted Workspace. Licensed under MIT.
"""Auto-generated from pandadoc_openapi.json — DO NOT EDIT BY HAND.

Re-generate via:
    python3 scripts/generate_pandadoc_tools.py

Maps every PandaDoc API operationId to its HTTP method, path, and
tag/module assignment. pandadoc_client.call() uses this table to
resolve which endpoint to hit.
"""

from __future__ import annotations

OPERATION_TABLE: dict[str, dict] = { 'accessToken': { 'deprecated': False,
                   'has_multipart': False,
                   'method': 'POST',
                   'module': 'misc',
                   'needs_polling': False,
                   'path': '/oauth2/access_token',
                   'tag': 'OAuth 2.0 Authentication'},
  'addDocumentRecipient': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'documents',
                            'needs_polling': False,
                            'path': '/public/v1/documents/{id}/recipients',
                            'tag': 'Document Recipients'},
  'addDsvNamedItems': { 'deprecated': False,
                        'has_multipart': False,
                        'method': 'POST',
                        'module': 'documents',
                        'needs_polling': False,
                        'path': '/public/v2/dsv/{document_id}/add-named-items',
                        'tag': 'Document Structure View'},
  'addMember': { 'deprecated': False,
                 'has_multipart': False,
                 'method': 'POST',
                 'module': 'workspace',
                 'needs_polling': False,
                 'path': '/public/v1/workspaces/{workspace_id}/members',
                 'tag': 'User and Workspace management'},
  'appendContentLibraryItemToDocument': { 'deprecated': False,
                                          'has_multipart': False,
                                          'method': 'POST',
                                          'module': 'documents',
                                          'needs_polling': False,
                                          'path': '/public/v1/documents/{id}/append-content-library-item',
                                          'tag': 'Documents'},
  'bulkDeleteDocuments': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'DELETE',
                           'module': 'documents',
                           'needs_polling': False,
                           'path': '/public/v1/documents',
                           'tag': 'Documents'},
  'changeDocumentStatus': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'PATCH',
                            'module': 'documents',
                            'needs_polling': False,
                            'path': '/public/v1/documents/{id}/status',
                            'tag': 'Documents'},
  'changeDocumentStatusWithUpload': { 'deprecated': False,
                                      'has_multipart': True,
                                      'method': 'PATCH',
                                      'module': 'documents',
                                      'needs_polling': False,
                                      'path': '/public/v1/documents/{id}/status?upload',
                                      'tag': 'Documents'},
  'createApiKey': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'POST',
                    'module': 'workspace',
                    'needs_polling': False,
                    'path': '/public/v1/workspaces/{workspace_id}/api-keys',
                    'tag': 'User and Workspace management'},
  'createCatalogItem': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'POST',
                         'module': 'content',
                         'needs_polling': False,
                         'path': '/public/v2/product-catalog/items',
                         'tag': 'Product catalog'},
  'createContact': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'POST',
                     'module': 'workspace',
                     'needs_polling': False,
                     'path': '/public/v1/contacts',
                     'tag': 'Contacts'},
  'createContentLibraryItem': { 'deprecated': False,
                                'has_multipart': False,
                                'method': 'POST',
                                'module': 'content',
                                'needs_polling': False,
                                'path': '/public/v1/content-library-items',
                                'tag': 'Content Library Items'},
  'createContentLibraryItemFromUpload': { 'deprecated': False,
                                          'has_multipart': True,
                                          'method': 'POST',
                                          'module': 'content',
                                          'needs_polling': False,
                                          'path': '/public/v1/content-library-items?upload',
                                          'tag': 'Content Library Items'},
  'createDocument': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'POST',
                      'module': 'documents',
                      'needs_polling': False,
                      'path': '/public/v1/documents',
                      'tag': 'Documents'},
  'createDocumentAttachment': { 'deprecated': False,
                                'has_multipart': False,
                                'method': 'POST',
                                'module': 'documents',
                                'needs_polling': False,
                                'path': '/public/v1/documents/{id}/attachments',
                                'tag': 'Document Attachments'},
  'createDocumentAttachmentFromFileUpload': { 'deprecated': False,
                                              'has_multipart': True,
                                              'method': 'POST',
                                              'module': 'documents',
                                              'needs_polling': False,
                                              'path': '/public/v1/documents/{id}/attachments?upload',
                                              'tag': 'Document Attachments'},
  'createDocumentEditingSession': { 'deprecated': False,
                                    'has_multipart': False,
                                    'method': 'POST',
                                    'module': 'documents',
                                    'needs_polling': False,
                                    'path': '/public/v1/documents/{id}/editing-sessions',
                                    'tag': 'Documents'},
  'createDocumentFields': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'documents',
                            'needs_polling': False,
                            'path': '/public/v1/documents/{id}/fields',
                            'tag': 'Document Fields'},
  'createDocumentFolder': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'workspace',
                            'needs_polling': False,
                            'path': '/public/v1/documents/folders',
                            'tag': 'Folders'},
  'createDocumentFromMarkdownUpload': { 'deprecated': False,
                                        'has_multipart': True,
                                        'method': 'POST',
                                        'module': 'documents',
                                        'needs_polling': False,
                                        'path': '/public/v1/documents?upload-markdown',
                                        'tag': 'Documents'},
  'createDocumentFromUpload': { 'deprecated': False,
                                'has_multipart': True,
                                'method': 'POST',
                                'module': 'documents',
                                'needs_polling': False,
                                'path': '/public/v1/documents?upload',
                                'tag': 'Documents'},
  'createDocumentLink': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'POST',
                          'module': 'documents',
                          'needs_polling': False,
                          'path': '/public/v1/documents/{id}/session',
                          'tag': 'Documents'},
  'createExportDocxTask': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'documents',
                            'needs_polling': False,
                            'path': '/public/beta/documents/{document_id}/docx-export-tasks',
                            'tag': 'Documents'},
  'createLinkedObject': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'POST',
                          'module': 'misc',
                          'needs_polling': False,
                          'path': '/public/v1/documents/{id}/linked-objects',
                          'tag': 'Document Link to CRM'},
  'createManualReminder': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'misc',
                            'needs_polling': False,
                            'path': '/public/v1/documents/{document_id}/send-reminder',
                            'tag': 'Document Reminders'},
  'createMemberToken': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'POST',
                         'module': 'workspace',
                         'needs_polling': False,
                         'path': '/public/v1/members/{member_id}/token',
                         'tag': 'Members'},
  'createNotarizationRequest': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'POST',
                                 'module': 'misc',
                                 'needs_polling': False,
                                 'path': '/public/v2/notary/notarization-requests',
                                 'tag': 'Notary'},
  'createTemplate': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'POST',
                      'module': 'templates',
                      'needs_polling': False,
                      'path': '/public/v1/templates',
                      'tag': 'Templates'},
  'createTemplateEditingSession': { 'deprecated': False,
                                    'has_multipart': False,
                                    'method': 'POST',
                                    'module': 'templates',
                                    'needs_polling': False,
                                    'path': '/public/v1/templates/{id}/editing-sessions',
                                    'tag': 'Templates'},
  'createTemplateFolder': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'workspace',
                            'needs_polling': False,
                            'path': '/public/v1/templates/folders',
                            'tag': 'Folders'},
  'createTemplateWithUpload': { 'deprecated': False,
                                'has_multipart': True,
                                'method': 'POST',
                                'module': 'templates',
                                'needs_polling': False,
                                'path': '/public/v1/templates?upload',
                                'tag': 'Templates'},
  'createUser': { 'deprecated': False,
                  'has_multipart': False,
                  'method': 'POST',
                  'module': 'workspace',
                  'needs_polling': False,
                  'path': '/public/v1/users',
                  'tag': 'User and Workspace management'},
  'createWebhookSubscription': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'POST',
                                 'module': 'webhooks',
                                 'needs_polling': False,
                                 'path': '/public/v1/webhook-subscriptions',
                                 'tag': 'Webhook subscriptions'},
  'createWorkspace': { 'deprecated': False,
                       'has_multipart': False,
                       'method': 'POST',
                       'module': 'workspace',
                       'needs_polling': False,
                       'path': '/public/v1/workspaces',
                       'tag': 'User and Workspace management'},
  'deactivateWorkspace': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'POST',
                           'module': 'workspace',
                           'needs_polling': False,
                           'path': '/public/v1/workspaces/{workspace_id}/deactivate',
                           'tag': 'User and Workspace management'},
  'deleteCatalogItem': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'DELETE',
                         'module': 'content',
                         'needs_polling': False,
                         'path': '/public/v2/product-catalog/items/{item_uuid}',
                         'tag': 'Product catalog'},
  'deleteContact': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'DELETE',
                     'module': 'workspace',
                     'needs_polling': False,
                     'path': '/public/v1/contacts/{id}',
                     'tag': 'Contacts'},
  'deleteDocument': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'DELETE',
                      'module': 'documents',
                      'needs_polling': False,
                      'path': '/public/v1/documents/{id}',
                      'tag': 'Documents'},
  'deleteDocumentAttachment': { 'deprecated': False,
                                'has_multipart': False,
                                'method': 'DELETE',
                                'module': 'documents',
                                'needs_polling': False,
                                'path': '/public/v1/documents/{id}/attachments/{attachment_id}',
                                'tag': 'Document Attachments'},
  'deleteDocumentRecipient': { 'deprecated': False,
                               'has_multipart': False,
                               'method': 'DELETE',
                               'module': 'documents',
                               'needs_polling': False,
                               'path': '/public/v1/documents/{id}/recipients/{recipient_id}',
                               'tag': 'Document Recipients'},
  'deleteLinkedObject': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'DELETE',
                          'module': 'misc',
                          'needs_polling': False,
                          'path': '/public/v1/documents/{id}/linked-objects/{linked_object_id}',
                          'tag': 'Document Link to CRM'},
  'deleteNotarizationRequest': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'DELETE',
                                 'module': 'misc',
                                 'needs_polling': False,
                                 'path': '/public/v2/notary/notarization-requests/{session_request_id}',
                                 'tag': 'Notary'},
  'deleteSection': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'DELETE',
                     'module': 'documents',
                     'needs_polling': False,
                     'path': '/public/v1/documents/{document_id}/sections/{section_id}',
                     'tag': 'Document Sections (Bundles)'},
  'deleteTemplate': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'DELETE',
                      'module': 'templates',
                      'needs_polling': False,
                      'path': '/public/v1/templates/{id}',
                      'tag': 'Templates'},
  'deleteWebhookSubscription': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'DELETE',
                                 'module': 'webhooks',
                                 'needs_polling': False,
                                 'path': '/public/v1/webhook-subscriptions/{id}',
                                 'tag': 'Webhook subscriptions'},
  'detailsContact': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'GET',
                      'module': 'workspace',
                      'needs_polling': False,
                      'path': '/public/v1/contacts/{id}',
                      'tag': 'Contacts'},
  'detailsContentLibraryItem': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'GET',
                                 'module': 'content',
                                 'needs_polling': False,
                                 'path': '/public/v1/content-library-items/{id}/details',
                                 'tag': 'Content Library Items'},
  'detailsCurrentMember': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'GET',
                            'module': 'workspace',
                            'needs_polling': False,
                            'path': '/public/v1/members/current',
                            'tag': 'Members'},
  'detailsDocument': { 'deprecated': False,
                       'has_multipart': False,
                       'method': 'GET',
                       'module': 'documents',
                       'needs_polling': False,
                       'path': '/public/v1/documents/{id}/details',
                       'tag': 'Documents'},
  'detailsDocumentAttachment': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'GET',
                                 'module': 'documents',
                                 'needs_polling': False,
                                 'path': '/public/v1/documents/{id}/attachments/{attachment_id}',
                                 'tag': 'Document Attachments'},
  'detailsLog': { 'deprecated': True,
                  'has_multipart': False,
                  'method': 'GET',
                  'module': 'misc',
                  'needs_polling': False,
                  'path': '/public/v1/logs/{id}',
                  'tag': 'API Logs'},
  'detailsLogV2': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'GET',
                    'module': 'misc',
                    'needs_polling': False,
                    'path': '/public/v2/logs/{id}',
                    'tag': 'API Logs'},
  'detailsMember': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'GET',
                     'module': 'workspace',
                     'needs_polling': False,
                     'path': '/public/v1/members/{id}',
                     'tag': 'Members'},
  'detailsTemplate': { 'deprecated': False,
                       'has_multipart': False,
                       'method': 'GET',
                       'module': 'templates',
                       'needs_polling': False,
                       'path': '/public/v1/templates/{id}/details',
                       'tag': 'Templates'},
  'detailsUser': { 'deprecated': False,
                   'has_multipart': False,
                   'method': 'GET',
                   'module': 'workspace',
                   'needs_polling': False,
                   'path': '/public/v1/users/{user_id}',
                   'tag': 'User and Workspace management'},
  'detailsWebhookEvent': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'GET',
                           'module': 'webhooks',
                           'needs_polling': False,
                           'path': '/public/v1/webhook-events/{id}',
                           'tag': 'Webhook events'},
  'detailsWebhookSubscription': { 'deprecated': False,
                                  'has_multipart': False,
                                  'method': 'GET',
                                  'module': 'webhooks',
                                  'needs_polling': False,
                                  'path': '/public/v1/webhook-subscriptions/{id}',
                                  'tag': 'Webhook subscriptions'},
  'documentESignDisclosure': { 'deprecated': False,
                               'has_multipart': False,
                               'method': 'GET',
                               'module': 'documents',
                               'needs_polling': False,
                               'path': '/public/v1/documents/{document_id}/esign-disclosure',
                               'tag': 'Documents'},
  'documentMoveToFolder': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'POST',
                            'module': 'documents',
                            'needs_polling': False,
                            'path': '/public/v1/documents/{id}/move-to-folder/{folder_id}',
                            'tag': 'Documents'},
  'documentRevertToDraft': { 'deprecated': False,
                             'has_multipart': False,
                             'method': 'POST',
                             'module': 'documents',
                             'needs_polling': False,
                             'path': '/public/v1/documents/{id}/draft',
                             'tag': 'Documents'},
  'documentSettingsGet': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'GET',
                           'module': 'documents',
                           'needs_polling': False,
                           'path': '/public/v2/documents/{document_id}/settings',
                           'tag': 'Document Settings'},
  'documentSettingsUpdate': { 'deprecated': False,
                              'has_multipart': False,
                              'method': 'PATCH',
                              'module': 'documents',
                              'needs_polling': False,
                              'path': '/public/v2/documents/{document_id}/settings',
                              'tag': 'Document Settings'},
  'downloadDocument': { 'deprecated': False,
                        'has_multipart': False,
                        'method': 'GET',
                        'module': 'documents',
                        'needs_polling': False,
                        'path': '/public/v1/documents/{id}/download',
                        'tag': 'Documents'},
  'downloadDocumentAttachment': { 'deprecated': False,
                                  'has_multipart': False,
                                  'method': 'GET',
                                  'module': 'documents',
                                  'needs_polling': False,
                                  'path': '/public/v1/documents/{id}/attachments/{attachment_id}/download',
                                  'tag': 'Document Attachments'},
  'downloadProtectedDocument': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'GET',
                                 'module': 'documents',
                                 'needs_polling': False,
                                 'path': '/public/v1/documents/{id}/download-protected',
                                 'tag': 'Documents'},
  'editDocumentRecipient': { 'deprecated': False,
                             'has_multipart': False,
                             'method': 'PATCH',
                             'module': 'documents',
                             'needs_polling': False,
                             'path': '/public/v1/documents/{id}/recipients/recipient/{recipient_id}',
                             'tag': 'Document Recipients'},
  'getCatalogItem': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'GET',
                      'module': 'content',
                      'needs_polling': False,
                      'path': '/public/v2/product-catalog/items/{item_uuid}',
                      'tag': 'Product catalog'},
  'getDocumentAutoReminderSettings': { 'deprecated': False,
                                       'has_multipart': False,
                                       'method': 'GET',
                                       'module': 'misc',
                                       'needs_polling': False,
                                       'path': '/public/v1/documents/{document_id}/auto-reminders',
                                       'tag': 'Document Reminders'},
  'getDocumentContent': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'GET',
                          'module': 'documents',
                          'needs_polling': True,
                          'path': '/public/beta/documents/{document_id}/content',
                          'tag': 'Documents'},
  'getDocumentSummary': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'GET',
                          'module': 'documents',
                          'needs_polling': True,
                          'path': '/public/beta/documents/{document_id}/summary',
                          'tag': 'Documents'},
  'getDocxExportTask': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'GET',
                         'module': 'documents',
                         'needs_polling': False,
                         'path': '/public/beta/documents/{document_id}/docx-export-tasks/{task_id}',
                         'tag': 'Documents'},
  'getWorkspacesList': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'GET',
                         'module': 'workspace',
                         'needs_polling': False,
                         'path': '/public/v1/workspaces',
                         'tag': 'User and Workspace management'},
  'listContacts': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'GET',
                    'module': 'workspace',
                    'needs_polling': False,
                    'path': '/public/v1/contacts',
                    'tag': 'Contacts'},
  'listContentLibraryItems': { 'deprecated': False,
                               'has_multipart': False,
                               'method': 'GET',
                               'module': 'content',
                               'needs_polling': False,
                               'path': '/public/v1/content-library-items',
                               'tag': 'Content Library Items'},
  'listDocumentAttachments': { 'deprecated': False,
                               'has_multipart': False,
                               'method': 'GET',
                               'module': 'documents',
                               'needs_polling': False,
                               'path': '/public/v1/documents/{id}/attachments',
                               'tag': 'Document Attachments'},
  'listDocumentAuditTrail': { 'deprecated': False,
                              'has_multipart': False,
                              'method': 'GET',
                              'module': 'documents',
                              'needs_polling': False,
                              'path': '/public/v2/documents/{document_id}/audit-trail',
                              'tag': 'Document Audit Trail'},
  'listDocumentFields': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'GET',
                          'module': 'documents',
                          'needs_polling': False,
                          'path': '/public/v1/documents/{id}/fields',
                          'tag': 'Document Fields'},
  'listDocumentFolders': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'GET',
                           'module': 'workspace',
                           'needs_polling': False,
                           'path': '/public/v1/documents/folders',
                           'tag': 'Folders'},
  'listDocuments': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'GET',
                     'module': 'documents',
                     'needs_polling': False,
                     'path': '/public/v1/documents',
                     'tag': 'Documents'},
  'listDocumentsByLinkedObject': { 'deprecated': False,
                                   'has_multipart': False,
                                   'method': 'GET',
                                   'module': 'misc',
                                   'needs_polling': False,
                                   'path': '/public/v1/documents/linked-objects',
                                   'tag': 'Document Link to CRM'},
  'listForm': { 'deprecated': False,
                'has_multipart': False,
                'method': 'GET',
                'module': 'content',
                'needs_polling': False,
                'path': '/public/v1/forms',
                'tag': 'Forms'},
  'listLinkedObjects': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'GET',
                         'module': 'misc',
                         'needs_polling': False,
                         'path': '/public/v1/documents/{id}/linked-objects',
                         'tag': 'Document Link to CRM'},
  'listLogs': { 'deprecated': True,
                'has_multipart': False,
                'method': 'GET',
                'module': 'misc',
                'needs_polling': False,
                'path': '/public/v1/logs',
                'tag': 'API Logs'},
  'listLogsV2': { 'deprecated': False,
                  'has_multipart': False,
                  'method': 'GET',
                  'module': 'misc',
                  'needs_polling': False,
                  'path': '/public/v2/logs',
                  'tag': 'API Logs'},
  'listMembers': { 'deprecated': False,
                   'has_multipart': False,
                   'method': 'GET',
                   'module': 'workspace',
                   'needs_polling': False,
                   'path': '/public/v1/members',
                   'tag': 'Members'},
  'listNotaries': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'GET',
                    'module': 'misc',
                    'needs_polling': False,
                    'path': '/public/v2/notary/notaries',
                    'tag': 'Notary'},
  'listNotarizationRequests': { 'deprecated': False,
                                'has_multipart': False,
                                'method': 'GET',
                                'module': 'misc',
                                'needs_polling': False,
                                'path': '/public/v2/notary/notarization-requests',
                                'tag': 'Notary'},
  'listRecentSmsOptOuts': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'GET',
                            'module': 'workspace',
                            'needs_polling': False,
                            'path': '/public/v1/sms-opt-outs',
                            'tag': 'Communication Preferences'},
  'listSections': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'GET',
                    'module': 'documents',
                    'needs_polling': False,
                    'path': '/public/v1/documents/{document_id}/sections',
                    'tag': 'Document Sections (Bundles)'},
  'listTemplateFolders': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'GET',
                           'module': 'workspace',
                           'needs_polling': False,
                           'path': '/public/v1/templates/folders',
                           'tag': 'Folders'},
  'listTemplates': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'GET',
                     'module': 'templates',
                     'needs_polling': False,
                     'path': '/public/v1/templates',
                     'tag': 'Templates'},
  'listUsers': { 'deprecated': False,
                 'has_multipart': False,
                 'method': 'GET',
                 'module': 'workspace',
                 'needs_polling': False,
                 'path': '/public/v1/users',
                 'tag': 'User and Workspace management'},
  'listWebhookEvent': { 'deprecated': False,
                        'has_multipart': False,
                        'method': 'GET',
                        'module': 'webhooks',
                        'needs_polling': False,
                        'path': '/public/v1/webhook-events',
                        'tag': 'Webhook events'},
  'listWebhookSubscriptions': { 'deprecated': False,
                                'has_multipart': False,
                                'method': 'GET',
                                'module': 'webhooks',
                                'needs_polling': False,
                                'path': '/public/v1/webhook-subscriptions',
                                'tag': 'Webhook subscriptions'},
  'notarizationRequestDetails': { 'deprecated': False,
                                  'has_multipart': False,
                                  'method': 'GET',
                                  'module': 'misc',
                                  'needs_polling': False,
                                  'path': '/public/v2/notary/notarization-requests/{session_request_id}',
                                  'tag': 'Notary'},
  'quoteUpdate': { 'deprecated': False,
                   'has_multipart': False,
                   'method': 'PUT',
                   'module': 'content',
                   'needs_polling': False,
                   'path': '/public/v1/documents/{document_id}/quotes/{quote_id}',
                   'tag': 'Quotes'},
  'reassignDocumentRecipient': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'POST',
                                 'module': 'documents',
                                 'needs_polling': False,
                                 'path': '/public/v1/documents/{id}/recipients/{recipient_id}/reassign',
                                 'tag': 'Document Recipients'},
  'removeMember': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'DELETE',
                    'module': 'workspace',
                    'needs_polling': False,
                    'path': '/public/v1/workspaces/{workspace_id}/members/{member_id}',
                    'tag': 'User and Workspace management'},
  'renameDocumentFolder': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'PUT',
                            'module': 'workspace',
                            'needs_polling': False,
                            'path': '/public/v1/documents/folders/{id}',
                            'tag': 'Folders'},
  'renameTemplateFolder': { 'deprecated': False,
                            'has_multipart': False,
                            'method': 'PUT',
                            'module': 'workspace',
                            'needs_polling': False,
                            'path': '/public/v1/templates/folders/{id}',
                            'tag': 'Folders'},
  'searchCatalogItems': { 'deprecated': False,
                          'has_multipart': False,
                          'method': 'GET',
                          'module': 'content',
                          'needs_polling': False,
                          'path': '/public/v2/product-catalog/items/search',
                          'tag': 'Product catalog'},
  'sectionDetails': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'GET',
                      'module': 'documents',
                      'needs_polling': False,
                      'path': '/public/v1/documents/{document_id}/sections/uploads/{upload_id}',
                      'tag': 'Document Sections (Bundles)'},
  'sectionInfo': { 'deprecated': False,
                   'has_multipart': False,
                   'method': 'GET',
                   'module': 'documents',
                   'needs_polling': False,
                   'path': '/public/v1/documents/{document_id}/sections/{section_id}',
                   'tag': 'Document Sections (Bundles)'},
  'sendDocument': { 'deprecated': False,
                    'has_multipart': False,
                    'method': 'POST',
                    'module': 'documents',
                    'needs_polling': False,
                    'path': '/public/v1/documents/{id}/send',
                    'tag': 'Documents'},
  'statusContentLibraryItem': { 'deprecated': False,
                                'has_multipart': False,
                                'method': 'GET',
                                'module': 'content',
                                'needs_polling': False,
                                'path': '/public/v1/content-library-items/{id}',
                                'tag': 'Content Library Items'},
  'statusDocument': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'GET',
                      'module': 'documents',
                      'needs_polling': False,
                      'path': '/public/v1/documents/{id}',
                      'tag': 'Documents'},
  'statusDocumentAutoReminder': { 'deprecated': False,
                                  'has_multipart': False,
                                  'method': 'GET',
                                  'module': 'misc',
                                  'needs_polling': False,
                                  'path': '/public/v1/documents/{document_id}/auto-reminders/status',
                                  'tag': 'Document Reminders'},
  'statusTemplate': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'GET',
                      'module': 'templates',
                      'needs_polling': False,
                      'path': '/public/v1/templates/{id}',
                      'tag': 'Templates'},
  'templateSettingsGet': { 'deprecated': False,
                           'has_multipart': False,
                           'method': 'GET',
                           'module': 'templates',
                           'needs_polling': False,
                           'path': '/public/v2/templates/{template_id}/settings',
                           'tag': 'Template Settings'},
  'templateSettingsUpdate': { 'deprecated': False,
                              'has_multipart': False,
                              'method': 'PATCH',
                              'module': 'templates',
                              'needs_polling': False,
                              'path': '/public/v2/templates/{template_id}/settings',
                              'tag': 'Template Settings'},
  'transferAllDocumentsOwnership': { 'deprecated': False,
                                     'has_multipart': False,
                                     'method': 'PATCH',
                                     'module': 'documents',
                                     'needs_polling': False,
                                     'path': '/public/v1/documents/ownership',
                                     'tag': 'Documents'},
  'transferDocumentOwnership': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'PATCH',
                                 'module': 'documents',
                                 'needs_polling': False,
                                 'path': '/public/v1/documents/{id}/ownership',
                                 'tag': 'Documents'},
  'updateCatalogItem': { 'deprecated': False,
                         'has_multipart': False,
                         'method': 'PATCH',
                         'module': 'content',
                         'needs_polling': False,
                         'path': '/public/v2/product-catalog/items/{item_uuid}',
                         'tag': 'Product catalog'},
  'updateContact': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'PATCH',
                     'module': 'workspace',
                     'needs_polling': False,
                     'path': '/public/v1/contacts/{id}',
                     'tag': 'Contacts'},
  'updateDocument': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'PATCH',
                      'module': 'documents',
                      'needs_polling': False,
                      'path': '/public/v1/documents/{id}',
                      'tag': 'Documents'},
  'updateDocumentAutoReminderSettings': { 'deprecated': False,
                                          'has_multipart': False,
                                          'method': 'PATCH',
                                          'module': 'misc',
                                          'needs_polling': False,
                                          'path': '/public/v1/documents/{document_id}/auto-reminders',
                                          'tag': 'Document Reminders'},
  'updateDocumentFieldsAssignment': { 'deprecated': False,
                                      'has_multipart': False,
                                      'method': 'PATCH',
                                      'module': 'documents',
                                      'needs_polling': False,
                                      'path': '/public/v1/documents/{id}/fields',
                                      'tag': 'Document Fields'},
  'updateTemplate': { 'deprecated': False,
                      'has_multipart': False,
                      'method': 'PATCH',
                      'module': 'templates',
                      'needs_polling': False,
                      'path': '/public/v1/templates/{id}',
                      'tag': 'Templates'},
  'updateWebhookSubscription': { 'deprecated': False,
                                 'has_multipart': False,
                                 'method': 'PATCH',
                                 'module': 'webhooks',
                                 'needs_polling': False,
                                 'path': '/public/v1/webhook-subscriptions/{id}',
                                 'tag': 'Webhook subscriptions'},
  'updateWebhookSubscriptionSharedKey': { 'deprecated': False,
                                          'has_multipart': False,
                                          'method': 'PATCH',
                                          'module': 'webhooks',
                                          'needs_polling': False,
                                          'path': '/public/v1/webhook-subscriptions/{id}/shared-key',
                                          'tag': 'Webhook subscriptions'},
  'uploadSection': { 'deprecated': False,
                     'has_multipart': False,
                     'method': 'POST',
                     'module': 'documents',
                     'needs_polling': False,
                     'path': '/public/v1/documents/{document_id}/sections/uploads',
                     'tag': 'Document Sections (Bundles)'},
  'uploadSectionWithUpload': { 'deprecated': False,
                               'has_multipart': True,
                               'method': 'POST',
                               'module': 'documents',
                               'needs_polling': False,
                               'path': '/public/v1/documents/{document_id}/sections/uploads?upload',
                               'tag': 'Document Sections (Bundles)'}}
