# © 2026 CoAssisted Workspace. Licensed under MIT.
"""PandaDoc Public API client — auth + transport + polling + multipart.

Single entry point for every PandaDoc API call. The MCP tools in
`tools/pandadoc_*.py` are thin Pydantic-wrapped shells around
`call(operation_id, **kwargs)`.

Auth precedence (Joshua 2026-05-01 answer to the auth question):
    1. config.pandadoc.api_key — if set, the Authorization header is
       built from it directly.
    2. OAuth2 refresh token — if api_key is unset and the OAuth trio
       (client_id, client_secret, refresh_token) is set, mint a fresh
       access_token on every call (PandaDoc tokens live ~60 minutes;
       we don't bother caching mid-session).
    3. Neither set → raise PandaDocAuthError. The user gets a clear
       error pointing at config.json.

The 122 endpoints carve up like this:
    Documents (26) + Attachments (6) + Sections (6) + Recipients (4)
        + Fields (3) + Settings (2) + Audit (1) + Structure (1)  = 49
    Templates (8) + Settings (2)                                 = 10
    User/Workspace (9) + Members (4) + Folders (6) + Contacts (5)
        + Comm Prefs (1)                                         = 25
    Content Library (5) + Product Catalog (5) + Forms (1) + Quotes (1) = 12
    Webhook Subs (6) + Events (2)                                = 8
    Notary (5) + Reminders (4) + CRM Links (4) + Logs (4) + OAuth (1) = 18
    Total: 122 (incl. 2 deprecated logs + 2 async polling)

The OPERATION_TABLE is generated from the OpenAPI spec at scaffold
time and committed to disk so we don't have to ship the 422 KB JSON
spec inside the MCP server (or re-parse it on every import).
"""

from __future__ import annotations

import json
import logging
import time
from typing import Any, Optional, Tuple

import config

try:
    from pandadoc_operations import OPERATION_TABLE  # type: ignore
except ImportError:
    # Generator hasn't run yet. The operation table lives in
    # pandadoc_operations.py and is regenerated by
    # scripts/generate_pandadoc_tools.py.
    OPERATION_TABLE: dict[str, dict] = {}

_log = logging.getLogger(__name__)


# =============================================================================
# Errors
# =============================================================================

class PandaDocError(Exception):
    """Base class for PandaDoc client errors."""


class PandaDocAuthError(PandaDocError):
    """Auth not configured or refused."""


class PandaDocAPIError(PandaDocError):
    """Non-2xx HTTP response from the API.

    Carries the full response payload so callers can surface the
    server-side error message.
    """

    def __init__(self, status_code: int, body: Any, message: str = ""):
        self.status_code = status_code
        self.body = body
        self.message = message or f"PandaDoc API returned {status_code}"
        super().__init__(self.message)


class PandaDocPollTimeout(PandaDocError):
    """An async (202) operation didn't complete inside the poll window."""


class UnknownOperationError(PandaDocError):
    """operation_id not in the generated OPERATION_TABLE."""


# =============================================================================
# Config helpers
# =============================================================================

def _cfg() -> dict:
    """Return the pandadoc config block, with defaults filled in."""
    block = config.get("pandadoc", {}) or {}
    if not isinstance(block, dict):
        return {}
    return block


def api_base() -> str:
    return _cfg().get("api_base") or "https://api.pandadoc.com"


def is_configured() -> Tuple[bool, str]:
    """Return (configured, reason). reason is empty when configured."""
    block = _cfg()
    if block.get("api_key"):
        return True, ""
    have_trio = all(
        block.get(k)
        for k in ("oauth_client_id", "oauth_client_secret", "oauth_refresh_token")
    )
    if have_trio:
        return True, ""
    return False, (
        "PandaDoc not configured. Set config.pandadoc.api_key in config.json, "
        "or supply oauth_client_id + oauth_client_secret + oauth_refresh_token "
        "for OAuth2 fallback."
    )


# =============================================================================
# Auth — API key preferred, OAuth2 refresh fallback
# =============================================================================

def _auth_header() -> str:
    """Return the Authorization header value.

    API key wins. OAuth fallback mints a fresh access_token via the
    refresh-token grant. Raises PandaDocAuthError on misconfig.
    """
    block = _cfg()
    api_key = block.get("api_key")
    if api_key:
        # PandaDoc expects "API-Key <key>". Allow callers to pre-prefix.
        if api_key.startswith("API-Key "):
            return api_key
        return f"API-Key {api_key}"

    # OAuth2 refresh-token flow.
    cid = block.get("oauth_client_id")
    cse = block.get("oauth_client_secret")
    rtok = block.get("oauth_refresh_token")
    if not (cid and cse and rtok):
        raise PandaDocAuthError(
            "PandaDoc auth not configured. Set config.pandadoc.api_key OR "
            "the full OAuth trio (oauth_client_id, oauth_client_secret, "
            "oauth_refresh_token)."
        )
    access = _refresh_oauth_token(cid, cse, rtok)
    return f"Bearer {access}"


def _refresh_oauth_token(client_id: str, client_secret: str, refresh_token: str) -> str:
    """Exchange a refresh_token for a fresh access_token.

    PandaDoc's token endpoint: POST /oauth2/access_token with
    grant_type=refresh_token + client_id + client_secret + refresh_token.
    """
    import urllib.parse
    import urllib.request
    body = urllib.parse.urlencode({
        "grant_type": "refresh_token",
        "client_id": client_id,
        "client_secret": client_secret,
        "refresh_token": refresh_token,
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{api_base()}/oauth2/access_token",
        data=body,
        method="POST",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:  # type: ignore
        try:
            err_body = json.loads(e.read().decode("utf-8"))
        except (json.JSONDecodeError, OSError):
            err_body = {"error": str(e)}
        raise PandaDocAuthError(
            f"OAuth refresh failed ({e.code}): {err_body}"
        ) from e
    except (urllib.error.URLError, OSError) as e:  # type: ignore
        raise PandaDocAuthError(f"OAuth refresh transport error: {e}") from e
    access = payload.get("access_token")
    if not access:
        raise PandaDocAuthError(
            f"OAuth refresh didn't return access_token: {payload}"
        )
    return access


# =============================================================================
# Transport
# =============================================================================

_RETRYABLE_STATUSES = {408, 429, 500, 502, 503, 504}


def _request(
    method: str,
    path: str,
    *,
    query: Optional[dict] = None,
    json_body: Any = None,
    multipart: Optional[list[tuple[str, tuple[str, bytes, str]]]] = None,
    extra_headers: Optional[dict] = None,
    timeout: int = 60,
) -> Tuple[int, dict, Any]:
    """Low-level HTTP — returns (status_code, response_headers, body).

    Body is JSON-decoded when content-type indicates JSON, otherwise
    raw bytes. Retries 408/429/5xx with exponential backoff per
    config.retry.

    Multipart uploads use a hand-built body to avoid pulling in
    `requests` as a dependency. Each part is (field_name,
    (filename, bytes_payload, content_type)).
    """
    import urllib.parse
    import urllib.request

    retry_cfg = config.retry_settings()
    max_attempts = int(retry_cfg.get("max_attempts", 4))
    initial = float(retry_cfg.get("initial_backoff_seconds", 1.0))
    max_backoff = float(retry_cfg.get("max_backoff_seconds", 30.0))

    url = api_base().rstrip("/") + path
    if query:
        clean = {k: v for k, v in query.items() if v is not None}
        if clean:
            url = url + ("&" if "?" in url else "?") + urllib.parse.urlencode(
                clean, doseq=True,
            )

    headers = {
        "Authorization": _auth_header(),
        "Accept": "application/json",
    }
    if extra_headers:
        headers.update(extra_headers)

    body_bytes: Optional[bytes] = None
    if multipart is not None:
        boundary = "----CoAssistedWorkspaceBoundary" + str(int(time.time() * 1000))
        body_bytes = _build_multipart_body(multipart, boundary)
        headers["Content-Type"] = f"multipart/form-data; boundary={boundary}"
    elif json_body is not None:
        body_bytes = json.dumps(json_body).encode("utf-8")
        headers["Content-Type"] = "application/json"

    last_err: Optional[Exception] = None
    for attempt in range(max_attempts):
        if attempt:
            backoff = min(max_backoff, initial * (2 ** (attempt - 1)))
            time.sleep(backoff)
        try:
            req = urllib.request.Request(
                url, data=body_bytes, method=method.upper(), headers=headers,
            )
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                raw = resp.read()
                ctype = resp.headers.get("Content-Type", "")
                body: Any
                if "json" in ctype:
                    body = json.loads(raw.decode("utf-8")) if raw else {}
                else:
                    body = raw
                return resp.status, dict(resp.headers), body
        except urllib.error.HTTPError as e:  # type: ignore
            try:
                err_raw = e.read()
                err_body: Any
                if "json" in (e.headers.get("Content-Type") or ""):
                    err_body = json.loads(err_raw.decode("utf-8"))
                else:
                    err_body = err_raw
            except (json.JSONDecodeError, OSError):
                err_body = {"error": str(e)}
            if e.code in _RETRYABLE_STATUSES and attempt + 1 < max_attempts:
                last_err = e
                _log.warning(
                    "PandaDoc %s %s returned %s; retrying (attempt %d/%d)",
                    method, path, e.code, attempt + 1, max_attempts,
                )
                continue
            raise PandaDocAPIError(
                e.code, err_body,
                f"PandaDoc {method} {path} returned {e.code}: {err_body}",
            ) from e
        except (urllib.error.URLError, OSError) as e:  # type: ignore
            last_err = e
            if attempt + 1 < max_attempts:
                _log.warning(
                    "PandaDoc %s %s transport error: %s; retrying",
                    method, path, e,
                )
                continue
            raise PandaDocAPIError(
                0, {"error": str(e)},
                f"PandaDoc transport error after {max_attempts} attempts: {e}",
            ) from e
    # Unreachable, but keep mypy happy.
    raise PandaDocAPIError(0, {"error": str(last_err) if last_err else "unknown"})


def _build_multipart_body(
    parts: list[tuple[str, tuple[str, bytes, str]]],
    boundary: str,
) -> bytes:
    """Hand-build a multipart/form-data body. No `requests` needed."""
    out: list[bytes] = []
    for field_name, (filename, payload, content_type) in parts:
        out.append(f"--{boundary}\r\n".encode("utf-8"))
        if filename is not None:
            out.append(
                f'Content-Disposition: form-data; name="{field_name}"; '
                f'filename="{filename}"\r\n'.encode("utf-8")
            )
            out.append(f"Content-Type: {content_type}\r\n\r\n".encode("utf-8"))
        else:
            out.append(
                f'Content-Disposition: form-data; name="{field_name}"\r\n\r\n'
                .encode("utf-8")
            )
        out.append(payload if isinstance(payload, bytes) else str(payload).encode("utf-8"))
        out.append(b"\r\n")
    out.append(f"--{boundary}--\r\n".encode("utf-8"))
    return b"".join(out)


# =============================================================================
# Public — call() — the one entry point every MCP tool uses
# =============================================================================

def call(
    operation_id: str,
    *,
    path_params: Optional[dict] = None,
    query: Optional[dict] = None,
    json_body: Any = None,
    multipart: Optional[list[tuple[str, tuple[str, bytes, str]]]] = None,
    poll: bool = False,
    poll_max_seconds: Optional[int] = None,
    poll_interval_seconds: Optional[float] = None,
) -> Any:
    """Invoke a PandaDoc API operation by operationId.

    `path_params` substitutes path placeholders. `query` and
    `json_body` are passed through as-is. `multipart` triggers
    multipart/form-data encoding for the 7 upload endpoints.

    `poll=True` enables 202-async polling. PandaDoc's two
    long-running endpoints (getDocumentSummary, getDocumentContent)
    return 202 + a Location header pointing at a status URL the
    client polls until 200. Tool wrappers for those endpoints
    pass `poll=True` automatically.
    """
    spec = OPERATION_TABLE.get(operation_id)
    if not spec:
        raise UnknownOperationError(
            f"Unknown PandaDoc operation_id: {operation_id!r}. "
            "Run scripts/generate_pandadoc_tools.py to refresh the table."
        )
    method = spec["method"]
    path = spec["path"]
    if path_params:
        for k, v in path_params.items():
            path = path.replace("{" + k + "}", str(v))

    status, headers, body = _request(
        method, path,
        query=query, json_body=json_body, multipart=multipart,
    )

    if poll and status == 202:
        return _poll_until_done(
            headers,
            poll_max_seconds=poll_max_seconds,
            poll_interval_seconds=poll_interval_seconds,
            initial_body=body,
        )
    return body


def _poll_until_done(
    headers: dict,
    *,
    poll_max_seconds: Optional[int],
    poll_interval_seconds: Optional[float],
    initial_body: Any,
) -> Any:
    """Follow a 202 response by polling its Location URL until 200.

    PandaDoc's pattern: 202 + Location header → keep GETting that
    URL with the same auth until it returns 200 with the real body.
    Times out via `poll_max_seconds` (config default 60s).
    """
    import urllib.error
    import urllib.request

    location = headers.get("Location") or headers.get("location")
    if not location:
        # No Location → just return the body the server gave us.
        return initial_body
    if not location.startswith("http"):
        location = api_base().rstrip("/") + location

    block = _cfg()
    max_s = poll_max_seconds if poll_max_seconds is not None else int(
        block.get("poll_max_seconds", 60)
    )
    interval = (
        poll_interval_seconds
        if poll_interval_seconds is not None
        else float(block.get("poll_interval_seconds", 1.0))
    )
    deadline = time.monotonic() + max_s

    while True:
        if time.monotonic() > deadline:
            raise PandaDocPollTimeout(
                f"PandaDoc poll exceeded {max_s}s waiting on {location}"
            )
        req = urllib.request.Request(
            location, method="GET",
            headers={
                "Authorization": _auth_header(),
                "Accept": "application/json",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                if resp.status == 200:
                    raw = resp.read()
                    ctype = resp.headers.get("Content-Type", "")
                    if "json" in ctype:
                        return json.loads(raw.decode("utf-8")) if raw else {}
                    return raw
                # 202 → still in progress, sleep + loop.
        except urllib.error.HTTPError as e:  # type: ignore
            raise PandaDocAPIError(
                e.code, {"error": str(e)},
                f"PandaDoc poll {location} returned {e.code}",
            ) from e
        time.sleep(interval)
